title:              엔지니어 이은경 포트폴리오
email:              whddlto2782@gmail.com
description:        개발자가 아닌 엔지니어를 지향합니다.
author:             Lee Eungyeong
baseurl:            "/eungyeong-pionero"
url:                "https://rileyleee.github.io"

# Social Profiles
twitter_username: 
github_username: rileyleee
facebook_username: 
instagram_username: aaangyeong2  
linkedin_username: eungyeong-pionero

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
